name = "myapp"
compatibility_date = "2024-03-20"
# pages_build_output_dir = "dist" # Commented out for local development to avoid conflict with `-- npm run dev`

[[d1_databases]]
binding = "DB" # Available in your Pages Functions as env.DB
database_name = "myapp-db"
database_id = "d0f688e7-7273-4114-9e2f-e1f8dfb7da73" # We will replace this after running the wrangler command